import os
import time
from datetime import datetime

# --- CONFIGURATION ---
BASE_VAULT = "AI_Employee_Vault"
INBOX_DIR = os.path.join(BASE_VAULT, "Inbox")
NEEDS_ACTION_DIR = os.path.join(BASE_VAULT, "Needs_Action")
CHECK_INTERVAL = 5 

def ensure_directories():
    """Ensures the vault structure exists."""
    for folder in [INBOX_DIR, NEEDS_ACTION_DIR]:
        os.makedirs(folder, exist_ok=True)

def update_dashboard_pending(task_filename):
    """Adds a task to the Pending Tasks section in Dashboard.md."""
    dashboard_path = os.path.join(BASE_VAULT, "Dashboard.md")
    if not os.path.exists(dashboard_path):
        return

    with open(dashboard_path, "r") as f:
        content = f.read()

    # Ensure ## Pending Tasks section exists
    if "## Pending Tasks" not in content:
        if "## Tasks" in content:
            content = content.replace("## Tasks", "## Tasks\n\n## Pending Tasks")
        else:
            content = "## Pending Tasks\n" + content

    # Add task if not already there
    task_entry = f"- [ ] {task_filename}"
    if task_entry not in content:
        lines = content.split("\n")
        new_lines = []
        in_pending = False
        added = False
        for line in lines:
            new_lines.append(line)
            if "## Pending Tasks" in line:
                in_pending = True
                continue
            if in_pending and not added and (line.startswith("##") or line == lines[-1]):
                # Insert before next header or at the end if no more headers
                if line.startswith("##"):
                    new_lines.insert(-1, task_entry)
                else:
                    new_lines.append(task_entry)
                added = True
                in_pending = False
        
        if not added:
            new_lines.append(task_entry)
            
        content = "\n".join(new_lines)

    with open(dashboard_path, "w") as f:
        f.write(content)

def create_task_file(filename):
    """Creates a standardized task file in Needs_Action for the AI to process."""
    # Remove .md if it already exists in filename to avoid double extension
    base_name = filename[:-3] if filename.endswith(".md") else filename
    task_filename = f"task_{base_name}.md"
    task_path = os.path.join(NEEDS_ACTION_DIR, task_filename)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content = f"""---
type: file_review
status: pending
priority: medium
created_at: {timestamp}
related_file: ["{filename}"]
---

# Task File: Review {filename}

## Description
A new file named `{filename}` was added to the Inbox. It needs to be reviewed and categorized by the AI Employee.

## Checklist
- [ ] Open and read {filename}
- [ ] Determine if it needs to be moved to a specific project or folder
- [ ] Update Dashboard.md with progress
- [ ] Move this task to Done/

## Notes
- Automatically generated by Watcher Script.
"""
    try:
        with open(task_path, "w") as f:
            f.write(content)
        print(f"[{timestamp}] ACTION: Task generated for {filename}")
        update_dashboard_pending(task_filename)
    except Exception as e:
        print(f"[{timestamp}] ERROR: Failed to create task for {filename}: {e}")

def main():
    print(f"--- BRONZE TIER WATCHER ---")
    print(f"Monitoring: {INBOX_DIR} | Interval: {CHECK_INTERVAL}s")
    
    processed_files = set()

    while True:
        ensure_directories()
        
        try:
            # Scan for new files in Inbox
            files = [f for f in os.listdir(INBOX_DIR) if os.path.isfile(os.path.join(INBOX_DIR, f))]
            
            for file in files:
                base_name = file[:-3] if file.endswith(".md") else file
                task_file_name = f"task_{base_name}.md"
                task_exists = os.path.exists(os.path.join(NEEDS_ACTION_DIR, task_file_name))
                
                # If file is new and no task exists yet
                if file not in processed_files and not task_exists:
                    print(f"[{datetime.now().strftime('%H:%M:%S')}] DETECT: New file found: {file}")
                    create_task_file(file)
                    processed_files.add(file)
            
        except Exception as e:
            print(f"CRITICAL ERROR: {e}")
            
        time.sleep(CHECK_INTERVAL)

if __name__ == "__main__":
    main()
