#!/usr/bin/env python3
"""
LinkedIn Watcher - Monitors LinkedIn activity and creates tasks in AI Employee vault.
Uses Playwright for browser automation.
"""

import os
import sys
import time
import json
import logging
from datetime import datetime
from playwright.sync_api import sync_playwright

# Configuration
CHECK_INTERVAL = 300  # 5 minutes
INBOX_DIR = "AI_Employee_Vault/Inbox"
LOG_FILE = "logs/linkedin_watcher.log"
STATE_FILE = "logs/linkedin_watcher_state.json"

# Ensure directories exist
os.makedirs(INBOX_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


def load_env():
    """Load environment variables from .env file."""
    env_file = ".env"
    if not os.path.exists(env_file):
        logger.error(".env file not found. Create it with LINKEDIN_EMAIL and LINKEDIN_PASSWORD")
        return None, None
    
    env_vars = {}
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()
    
    return env_vars.get("LINKEDIN_EMAIL"), env_vars.get("LINKEDIN_PASSWORD")


def load_state():
    """Load processed activity IDs from state file."""
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            logger.warning("State file corrupted, starting fresh")
    return {"processed_ids": []}


def save_state(state):
    """Save processed activity IDs to state file."""
    try:
        with open(STATE_FILE, "w") as f:
            json.dump(state, f, indent=2)
    except IOError as e:
        logger.error(f"Failed to save state: {e}")


def sanitize_filename(name, max_length=50):
    """Create a safe filename."""
    import re
    safe_name = re.sub(r'[^\w\s-]', '', name)
    safe_name = re.sub(r'[\s]+', '_', safe_name)
    return safe_name[:max_length].strip('_')


def create_task_file(contact_name, contact_title, activity_type, details, activity_id):
    """Create a task file in the Inbox directory."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    name_slug = sanitize_filename(contact_name) if contact_name else "unknown"
    filename = f"linkedin_{activity_type}_{timestamp}_{name_slug}.md"
    filepath = os.path.join(INBOX_DIR, filename)
    
    priority = "high" if activity_type == "new_connection" else "medium"
    
    content = f"""---
type: linkedin_{activity_type}
status: pending
priority: {priority}
created_at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
contact_name: {contact_name}
contact_title: {contact_title}
activity_type: {activity_type}
activity_id: {activity_id}
---

# LinkedIn Task: {activity_type.replace('_', ' ').title()} - {contact_name or 'Unknown'}

## Details
- **Contact**: {contact_name or 'Unknown'}
- **Title**: {contact_title or 'N/A'}
- **Activity Type**: {activity_type.replace('_', ' ').title()}
- **Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Activity Details
{details}

## Suggested Actions
- [ ] Review activity details
- [ ] Take appropriate action (respond, connect, follow-up)
- [ ] Move to Done when complete

---
*Automatically generated by LinkedIn Watcher*
"""
    
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Created task file: {filename}")
        return True
    except IOError as e:
        logger.error(f"Failed to create task file: {e}")
        return False


def check_linkedin(page, email, password, state):
    """Check LinkedIn for new activity."""
    new_activities = []
    
    try:
        # Navigate to LinkedIn
        page.goto("https://www.linkedin.com", timeout=30000)
        page.wait_for_timeout(3000)
        
        # Check if already logged in by looking for navigation elements
        current_url = page.url
        if "login" in current_url or "signin" in current_url:
            logger.info("Not logged in, attempting login...")
            try:
                # Fill login form
                page.fill("#username", email)
                page.fill("#password", password)
                page.click('button[type="submit"]')
                page.wait_for_timeout(5000)
            except Exception as e:
                logger.error(f"Login failed: {e}")
                return False
        
        # Check for new notifications
        try:
            # Click on notifications bell
            page.click('button[aria-label="Notifications"]', timeout=5000)
            page.wait_for_timeout(2000)
            
            # Look for notification items
            notifications = page.query_selector_all('.notifications-list li')
            
            for notif in notifications[:5]:  # Process last 5 notifications
                try:
                    activity_text = notif.inner_text()
                    activity_id = hash(activity_text)
                    
                    if str(activity_id) not in state["processed_ids"]:
                        # Parse notification to extract details
                        if "connected" in activity_text.lower():
                            activity_type = "new_connection"
                            # Extract name (simplified parsing)
                            parts = activity_text.split()
                            contact_name = parts[0] if parts else "Unknown Connection"
                            contact_title = "New Connection"
                            details = activity_text
                        elif "message" in activity_text.lower():
                            activity_type = "new_message"
                            contact_name = "LinkedIn Member"
                            contact_title = "N/A"
                            details = activity_text
                        elif "viewed your profile" in activity_text.lower():
                            activity_type = "profile_view"
                            contact_name = "Profile Viewer"
                            contact_title = "N/A"
                            details = activity_text
                        else:
                            activity_type = "other_activity"
                            contact_name = "LinkedIn Activity"
                            contact_title = "N/A"
                            details = activity_text
                        
                        new_activities.append({
                            "contact_name": contact_name,
                            "contact_title": contact_title,
                            "activity_type": activity_type,
                            "details": details,
                            "activity_id": str(activity_id)
                        })
                except Exception as e:
                    logger.warning(f"Error processing notification: {e}")
                    continue
            
            # Close notifications panel
            page.keyboard.press("Escape")
            page.wait_for_timeout(1000)
            
        except Exception as e:
            logger.warning(f"Could not access notifications: {e}")
        
        # Check for new messages in messaging panel
        try:
            page.click('button[aria-label="Messaging"]', timeout=5000)
            page.wait_for_timeout(2000)
            
            # Look for unread messages
            messages = page.query_selector_all('.msg-conversation-card')
            
            for msg in messages[:3]:  # Check last 3 messages
                try:
                    msg_text = msg.inner_text()
                    msg_id = hash(msg_text)
                    
                    if str(msg_id) not in state["processed_ids"] and "unread" in msg_text.lower():
                        new_activities.append({
                            "contact_name": "LinkedIn Contact",
                            "contact_title": "N/A",
                            "activity_type": "new_message",
                            "details": msg_text,
                            "activity_id": str(msg_id)
                        })
                except Exception as e:
                    logger.warning(f"Error processing message: {e}")
                    continue
            
            # Close messaging panel
            page.keyboard.press("Escape")
            page.wait_for_timeout(1000)
            
        except Exception as e:
            logger.warning(f"Could not access messaging: {e}")
        
        return new_activities
        
    except Exception as e:
        logger.error(f"Error checking LinkedIn: {e}")
        return False


def main():
    """Main watcher loop."""
    logger.info("=" * 50)
    logger.info("LinkedIn Watcher started")
    logger.info(f"Monitoring: LinkedIn Activity")
    logger.info(f"Check interval: {CHECK_INTERVAL}s")
    logger.info(f"Task output: {INBOX_DIR}")
    logger.info("=" * 50)
    
    email, password = load_env()
    if not email or not password:
        logger.error("LinkedIn credentials not found. Exiting.")
        return
    
    state = load_state()
    
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            viewport={"width": 1280, "height": 720},
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        )
        page = context.new_page()
        
        logger.info("Browser initialized. Starting monitoring loop...")
        
        while True:
            try:
                activities = check_linkedin(page, email, password, state)
                
                if activities:
                    logger.info(f"Found {len(activities)} new activity/activities")
                    
                    for activity in activities:
                        if create_task_file(
                            activity["contact_name"],
                            activity["contact_title"],
                            activity["activity_type"],
                            activity["details"],
                            activity["activity_id"]
                        ):
                            state["processed_ids"].append(activity["activity_id"])
                    
                    save_state(state)
                    logger.info(f"Processed {len(activities)} new activity/activities")
                else:
                    logger.info("No new activities found")
                
            except KeyboardInterrupt:
                logger.info("Shutting down LinkedIn Watcher...")
                break
            except Exception as e:
                logger.error(f"Error in main loop: {e}")
            
            time.sleep(CHECK_INTERVAL)
        
        browser.close()


if __name__ == "__main__":
    main()
