#!/usr/bin/env python3
"""
Gmail Watcher - Monitors Gmail inbox for new emails and creates tasks in AI Employee vault.
Uses IMAP protocol to check for unread emails.
"""

import os
import sys
import time
import imaplib
import email
from email.header import decode_header
from datetime import datetime
import json
import re
import logging

# Configuration
CHECK_INTERVAL = 60  # seconds
INBOX_DIR = "AI_Employee_Vault/Inbox"
LOG_FILE = "logs/gmail_watcher.log"
STATE_FILE = "logs/gmail_watcher_state.json"

# Ensure directories exist
os.makedirs(INBOX_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


def load_env():
    """Load environment variables from .env file."""
    env_file = ".env"
    if not os.path.exists(env_file):
        logger.error(".env file not found. Create it with GMAIL_ADDRESS and GMAIL_APP_PASSWORD")
        return None, None
    
    env_vars = {}
    with open(env_file, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                env_vars[key.strip()] = value.strip()
    
    return env_vars.get("GMAIL_ADDRESS") or env_vars.get("EMAIL_ADDRESS"), env_vars.get("GMAIL_APP_PASSWORD") or env_vars.get("EMAIL_PASSWORD") or env_vars.get("EMAIL_APP_PASSWORD")


def load_state():
    """Load processed email IDs from state file."""
    if os.path.exists(STATE_FILE):
        try:
            with open(STATE_FILE, "r") as f:
                return json.load(f)
        except (json.JSONDecodeError, IOError):
            logger.warning("State file corrupted, starting fresh")
    return {"processed_ids": []}


def save_state(state):
    """Save processed email IDs to state file."""
    try:
        with open(STATE_FILE, "w") as f:
            json.dump(state, f, indent=2)
    except IOError as e:
        logger.error(f"Failed to save state: {e}")


def decode_mime_header(header_value):
    """Decode MIME header with proper encoding handling."""
    if header_value is None:
        return ""
    
    decoded_parts = decode_header(header_value)
    result = []
    
    for part, charset in decoded_parts:
        if isinstance(part, bytes):
            try:
                result.append(part.decode(charset or "utf-8", errors="replace"))
            except (LookupError, UnicodeDecodeError):
                result.append(part.decode("utf-8", errors="replace"))
        else:
            result.append(part)
    
    return "".join(result)


def sanitize_filename(name, max_length=50):
    """Create a safe filename from email subject."""
    # Remove special characters and limit length
    safe_name = re.sub(r'[^\w\s-]', '', name)
    safe_name = re.sub(r'[\s]+', '_', safe_name)
    return safe_name[:max_length].strip('_')


def create_task_file(sender, subject, date, body_snippet, email_id):
    """Create a task file in the Inbox directory."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    subject_slug = sanitize_filename(subject) if subject else "no_subject"
    filename = f"email_{timestamp}_{subject_slug}.md"
    filepath = os.path.join(INBOX_DIR, filename)
    
    # Truncate body snippet if too long
    if len(body_snippet) > 500:
        body_snippet = body_snippet[:500] + "..."
    
    content = f"""---
type: email
status: pending
priority: medium
created_at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
sender: {sender}
subject: {subject}
email_id: {email_id}
---

# Email Task: {subject or 'No Subject'}

## Details
- **From**: {sender}
- **Received**: {date}
- **Subject**: {subject or 'No Subject'}

## Content Preview
{body_snippet or '[No content preview available]'}

## Actions Required
- [ ] Review email content
- [ ] Determine appropriate response or action
- [ ] Move to Done when complete

---
*Automatically generated by Gmail Watcher*
"""
    
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        logger.info(f"Created task file: {filename}")
        return True
    except IOError as e:
        logger.error(f"Failed to create task file: {e}")
        return False


def check_gmail():
    """Check Gmail for new unread emails."""
    email_address, app_password = load_env()
    
    if not email_address or not app_password:
        logger.error("Gmail credentials not found in .env file")
        return False
    
    try:
        # Connect to Gmail IMAP
        mail = imaplib.IMAP4_SSL("imap.gmail.com", 993)
        mail.login(email_address, app_password)
        mail.select("INBOX")
        
        # Search for unseen emails
        status, messages = mail.search(None, "UNSEEN")
        
        if status != "OK":
            logger.warning("Failed to search emails")
            return False
        
        email_ids = messages[0].split()
        
        if not email_ids:
            logger.info("No new emails found")
            return True
        
        logger.info(f"Found {len(email_ids)} new email(s)")
        
        state = load_state()
        new_emails_count = 0
        
        for email_id in email_ids:
            email_id_str = email_id.decode("utf-8")
            
            # Skip if already processed
            if email_id_str in state["processed_ids"]:
                continue
            
            # Fetch email
            status, msg_data = mail.fetch(email_id, "(RFC822)")
            
            if status != "OK":
                logger.warning(f"Failed to fetch email {email_id_str}")
                continue
            
            # Parse email
            raw_email = msg_data[0][1]
            msg = email.message_from_bytes(raw_email)
            
            # Extract headers
            sender = decode_mime_header(msg.get("From"))
            subject = decode_mime_header(msg.get("Subject"))
            date = decode_mime_header(msg.get("Date"))
            
            # Extract body snippet
            body_snippet = ""
            if msg.is_multipart():
                for part in msg.walk():
                    content_type = part.get_content_type()
                    if content_type == "text/plain":
                        payload = part.get_payload(decode=True)
                        if payload:
                            try:
                                body_snippet = payload.decode("utf-8", errors="replace")
                                break
                            except Exception:
                                pass
            else:
                payload = msg.get_payload(decode=True)
                if payload:
                    body_snippet = payload.decode("utf-8", errors="replace")
            
            # Create task file
            if create_task_file(sender, subject, date, body_snippet, email_id_str):
                state["processed_ids"].append(email_id_str)
                new_emails_count += 1
                
                # Mark as seen to prevent re-processing
                mail.store(email_id, "+FLAGS", "\\Seen")
        
        save_state(state)
        logger.info(f"Processed {new_emails_count} new email(s)")
        
        # Cleanup
        mail.close()
        mail.logout()
        
        return True
        
    except imaplib.IMAP4.error as e:
        logger.error(f"IMAP error: {e}")
        return False
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        return False


def main():
    """Main watcher loop."""
    logger.info("=" * 50)
    logger.info("Gmail Watcher started")
    logger.info(f"Monitoring: Gmail INBOX")
    logger.info(f"Check interval: {CHECK_INTERVAL}s")
    logger.info(f"Task output: {INBOX_DIR}")
    logger.info("=" * 50)
    
    while True:
        try:
            check_gmail()
        except KeyboardInterrupt:
            logger.info("Shutting down Gmail Watcher...")
            break
        except Exception as e:
            logger.error(f"Error in main loop: {e}")
        
        time.sleep(CHECK_INTERVAL)


if __name__ == "__main__":
    main()
